### ISSUE TITLE
People typing /spawn and glitching

### ISSUE THREAD

**Issue by Murabitos** [gravitylow/AntiCheat#29]
When people on my server type /spawn, they should go to a floating platform in the sky. They can jump down onto the terrain and PvP. Below the terrain is a huge carved out area lined by glowstone. This makes it so people's clients don't have to load as many blocks and there aren't really any lighting updates down there. However, it seems that some people shoot all the way below the platform (which is actually a bunch of skyships) and then all the way through the terrain into the glowstone outline which is just above bedrock. When one player did this (it doesn't happen every time), I made sure to check the console and this is what it said.

2012-06-03 08:55:58 [SEVERE] [AntiCheat] vnny28p tried to fly on y-axis 

I was also told this happened while a player was going through a portal to the nether. ALSO, when a player is on the edge of spawn, even sneaking, it shoots them down without an error at all.

I think that players might even be shooting into the void, however I have a plugin called Safe Void that prevents players from falling into the void. But either way, AntiCheat seems to think players are flying when they're teleporting.. Even going to the nether through a netherportal. My home plugin that I use is called MultiHome, but I think that's irrelevant.

**Comment by Rojoss** [comment]
I can confirm it's not fully fixed for me either.
And make sure to look in to the glitching issue.
Since it's not normal that if something get blocked that you glitch in the ground/void.

**Comment by gravitylow** [comment]
Alright, this sounds really weird but I'll look into it. I could have sworn most of the teleportation issues were fixed, or at least we were told so.

**Comment by Murabitos** [comment]
Haha well thanks for looking at it, it's only started happening since my server switched to using AntiCheat.

**Comment by Rojoss** [comment]
Yeah i thought it was fixed with last devs but players where still complaining about it on our forums though.
I made a post where ppl can report Anticheat bugs so hope you don't call me annoying for posting so much just trying to help get this stable as much as possible.
It's easier to get report from 100 ppl then 1 player testing.

**Comment by Murabitos** [comment]
I need it stable too, post away.

**Comment by SuperSpyTX** [comment]
Please try this build http://ci.h31ix.net/job/AntiCheat/147/ and report back with results.

I'm not marking this as fixed this time.

**Comment by Murabitos** [comment]
Alright I put it on my server, I'll let you know if it's happening to people still.

**Comment by Murabitos** [comment]
Okay so far nobody is getting shot into the void area below spawn when typing /spawn, but people who are on the edge of spawn are still getting shot down onto the ground even if they hold shift.

**Comment by SuperSpyTX** [comment]
@Her-Craving Console Logs?

Also if you can, are you able to hop onto IRC?

**Comment by Murabitos** [comment]
I -could- hop on IRC, but could you instead hop onto my TS server? Gioboi.ts.nfoservers.com

**Comment by SuperSpyTX** [comment]
@Her-Craving Seems you were busy at the time I hopped on.

**Comment by Murabitos** [comment]
I was just in the bathroom LOL come back!

**Comment by SuperSpyTX** [comment]
@Her-Craving's issue on this is fixed.

I'm now waiting for @worstboy32

**Comment by Rojoss** [comment]
Adding it to my servers will let you know the results.

**Comment by Rojoss** [comment]
Haven't got a report yet from users so i guess it's fixed.

**Comment by Rojoss** [comment]
It's still happening did got 3 reports the last 2 days.
Players do /spawn and fall in the void or tp xx blocks down.

**Comment by SuperSpyTX** [comment]
@worstboy32 Sounds outdated build.
